spring.application.name=user
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/ms-user
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update


spring.rabbitmq.addresses=amqps://yuumxntf:msaba23a7Od2DP8zkV5izb5XAWPkl3p_@chimpanzee.rmq.cloudamqp.com/yuumxntf
broker.queue.email.name=default.email





